name: Create Git Tag

on:
  workflow_run:
    workflows: ["Auto-generate Semantic Tags"]
    types:
      - completed

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine version
        id: tag
        run: |
          branch_name=${{ github.event.workflow_run.head_branch }}
          tag=${{ github.event.workflow_run.outputs.tag }}
          echo "::set-output name=tag::${tag}"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Git Login
        uses: actions/github-script@v4
        with:
          access_token: ${{ github.token }}
          script: |
            const { execSync } = require('child_process');
            execSync('git remote set-url origin https://github.com/${{ github.repository }}.git');

      - name: Create Git Tag
        run: |
          git tag ${{ needs.create-tag.outputs.tag }}
          git push origin ${{ needs.create-tag.outputs.tag }}
