name: Auto-generate Semantic Tags

on:
  push:
    branches:
      - '*'

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version
        id: tag
        run: |
          last_tag=$(git describe --tags --abbrev=0)
          version=$(echo $last_tag | awk -F. '{print $1"."$2"."$3+1}')
          tag=$(git log --oneline $last_tag..HEAD --grep="(feat|fix)(\(.+\))?:\s(.+)" --pretty=format:"${version}")
          if [[ -z "$tag" ]]; then
            tag=$last_tag
          fi
          echo "::set-output name=tag::${tag}"

  build-and-push:
    needs: determine-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ github.repository }}:${{ github.ref_slug }}-${{ needs.determine-version.outputs.tag }}
          docker push ${{ github.repository }}:${{ github.ref_slug }}-${{ needs.determine-version.outputs.tag }}
