name: Auto-generate Semantic Tags

on:
  push:
    branches:
      - '*' # Trigger on all branches

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version
        id: tag
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          if [[ "$last_tag" == "v0.0.0" ]]; then
            tag="v0.0.1"
          else
            version=$(echo "$last_tag" | awk -F. '{print $1"."$2"."$3+1}')
            tag=$(git log --oneline "$last_tag"..HEAD --pretty=format:"${version}")
          fi
          echo "::set-output name=tag::${branch_name}-${tag}"

  build-and-push:
    needs: determine-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Docker credentials
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          repository_name=$(basename "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          image_tag="${repository_name}-${GITHUB_REF##*/}-${{ needs.determine-version.outputs.tag }}"
          docker build . --file Dockerfile --tag "ghcr.io/${{ github.repository }}/${image_tag}"
          docker push "ghcr.io/${{ github.repository }}/${image_tag}"
