name: Auto-generate Semantic Tags

on:
  push:
    branches:
      - '*' # Trigger on all branches

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine version
        id: tag
        run: |
          branch_name=${{ github.ref }}
          branch_name=$(echo "$branch_name" | awk '{print tolower($0)}') # Convert branch name to lowercase
          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          if [[ "$last_tag" == "v0.0.0" ]]; then
            tag="v0.0.1"
          else
            version=$(echo "$last_tag" | awk -F. '{$NF+=1; OFS="."; print $0}')
            tag=$(git log --oneline "$last_tag"..HEAD --pretty=format:"${version}")
          fi
          tag=$(echo "$tag" | awk '{print tolower($0)}') # Convert tag to lowercase
          echo "::set-output name=tag::${branch_name}-${tag}"

  build-and-push:
    needs: determine-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker credentials
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          repository_name=$(echo "${{ github.repository }}" | awk '{print tolower($0)}') # Convert repository name to lowercase
          branch_name=${{ github.ref }}
          branch_name=$(echo "$branch_name" | awk '{print tolower($0)}') # Convert branch name to lowercase
          image_tag="${branch_name}-${{ needs.determine-version.outputs.tag }}"
          image_tag=$(echo "$image_tag" | awk '{print tolower($0)}') # Convert image tag to lowercase
          docker build . --file Dockerfile --tag "ghcr.io/${repository_name}/${image_tag}"
          docker push "ghcr.io/${repository_name}/${image_tag}"
