name: Docker Image CI

on:
  push:
    branches:
      - dockerfile
  pull_request:
    branches:
      - dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.ref_slug }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Packages
        run: docker push ${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.ref_slug }}
